name: Build and test

on:
  push:
    branches-ignore:
      - sandbox/**
    paths-ignore:
      - retrospectives/**
      - assets/**
      - bin/**
      - .vscode/**
      - README.md
      - .hive

  pull_request:
    branches: [main]

jobs:
  # build:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Setup .NET
  #       uses: actions/setup-dotnet@v1
  #       with:
  #         dotnet-version: 5.0.x
  #     - name: Restore dependencies
  #       run: dotnet restore
  #     - name: Build
  #       run: dotnet build --no-restore
  #     - name: Test
  #       run: dotnet test Principal.Website.Tests --filter "Category!=Database" --no-build -l:junit;LogFilePath=TestResults/TestResults.xml
  #     - name: Publish Unit Test Results
  #       uses: EnricoMi/publish-unit-test-result-action@v1.23
  #       if: always()
  #       with:
  #         files: /home/runner/work/site/site/**.Tests/TestResults/**.xml
  #         check_name: Unit Test Results

  inspect:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: install npm dependencies
        run: npm ci
      - name: check format for entire solution
        run: npm run format
      - name: check linting
        run: npm run lint
      - name: check duplicates
        run: npm run cpd
